### ISSUE TITLE
Raw string for syntax errors

### ISSUE THREAD

**Issue by seanmacb** [otavioalonso/pomodoro#1]
[This line](https://github.com/otavioalonso/pomodoro/blob/2d188ed6a26b36c715baa77a2d58116a1f3cf3ef/pomodoro.py#L109) needs to be a raw string - I'm getting syntax errors

**Comment by seanmacb** [comment]
I want a refund!

**Comment by otavioalonso** [comment]
Thanks, brotha!
Pushed the modification to the main repo.
And your refund is ready. You can get it in my office.
